---
title: "highUnc-vignette"
author: "Samuel Chang"
date: "3/5/2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{highUnc-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# 1. Load the occUncertain R package and data set
```{r}
library(occUncertain)

load("../data/L_wiedii_highUnc.RData")

highUnc_observed <-
  dplyr::select(L_wiedii_highUnc,
    decimalLatitude,
    decimalLongitude,
    species)

data(land)
highUnc.IUCN <- IUCN.eval(highUnc_observed, exclude.area = T, write_results = F)
highUnc.EOO <- highUnc.IUCN$EOO
highUnc.AOO <- highUnc.IUCN$AOO
```

# 2. meters_to_decdeg function
```{r uncertainty from meter to radian degrees}
#NA as Zero
highUnc_naZero <-
  meters_to_decdeg(
    L_wiedii_highUnc,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as 0"
  )

highUnc_naZero <-
  cbind(L_wiedii_highUnc, highUnc_naZero)

highUnc_naZero <- dplyr::select(
  highUnc_naZero,
  decimalLatitude,
  decimalLongitude,
  lon_uncertainty,
  lat_uncertainty,
  species
)

#NA as Mean
highUnc_naMean <-
  meters_to_decdeg(
    L_wiedii_highUnc,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as mean"
  )

highUnc_naMean <-
  cbind(L_wiedii_highUnc, highUnc_naMean)

highUnc_naMean <- dplyr::select(
  highUnc_naMean,
  decimalLatitude,
  decimalLongitude,
  lon_uncertainty,
  lat_uncertainty,
  species
)

#NA as NA
highUnc_naNA <-
  meters_to_decdeg(
    L_wiedii_highUnc,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as NA"
  )

highUnc_naNA <-
  cbind(L_wiedii_highUnc, highUnc_naNA)

highUnc_naNA <-
  dplyr::filter(highUnc_naNA,!is.na(coordinateUncertaintyInMeters))
highUnc_naNA <- dplyr::select(
  highUnc_naNA,
  decimalLatitude,
  decimalLongitude,
  lon_uncertainty,
  lat_uncertainty,
  species
)
```

# 3. Using the random occurrences in land metrics with random_geo_range

`NA as Mean`
```{r highUnc_naMean geographic metrics}
----#1000
highUnc_naMean_geo_range_1000 <-
  random_geo_range(
    1000,
    highUnc_naMean,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(highUnc_naMean_geo_range_1000)[1] <- "naMean_EOO"
names(highUnc_naMean_geo_range_1000)[2] <- "naMean_AOO"

#Z-stat
## EOO
(highUnc.EOO - mean(highUnc_naMean_geo_range_1000$naMean_EOO)) / sd(highUnc_naMean_geo_range_1000$naMean_EOO)

#histogram
hist(highUnc_naMean_geo_range_1000$naMean_EOO,
  main = "L. wiedii extent of occurrence, with mean uncertainty values for NA cells")
abline(v = highUnc.EOO,
  col = "red")

#Z-stat
## AOO
(highUnc.AOO - mean(highUnc_naMean_geo_range_1000$naMean_AOO)) / sd(highUnc_naMean_geo_range_1000$naMean_AOO)

#histogram
hist(highUnc_naMean_geo_range_1000$naMean_AOO,
  main = "L. wiedii area of occupancy, with mean uncertainty values for NA cells")
abline(v = highUnc.AOO,
  col = "red")

----#100
highUnc_naMean_geo_range_100 <-
  random_geo_range(
    100,
    highUnc_naMean,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(highUnc_naMean_geo_range_100)[1] <- "naMean_EOO"
names(highUnc_naMean_geo_range_100)[2] <- "naMean_AOO"

#Z-stat
## EOO
(highUnc.EOO - mean(highUnc_naMean_geo_range_100$naMean_EOO)) / sd(highUnc_naMean_geo_range_100$naMean_EOO)

#histogram
hist(highUnc_naMean_geo_range_100$naMean_EOO,
  main = "L. wiedii extent of occurrence, with mean uncertainty values for NA cells")
abline(v = highUnc.EOO,
  col = "red")

#Z-stat
## AOO
(highUnc.AOO - mean(highUnc_naMean_geo_range_100$naMean_AOO)) / sd(highUnc_naMean_geo_range_100$naMean_AOO)

#histogram
hist(highUnc_naMean_geo_range_100$naMean_AOO,
  main = "L. wiedii area of occupancy, with mean uncertainty values for NA cells")
abline(v = highUnc.AOO,
  col = "red")
```

`naZero`
```{r highUnc_naZero_geo_range}
----#1000
highUnc_naZero_geo_range_1000 <-
  random_geo_range(
    1000,
    highUnc_naZero,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(highUnc_naZero_geo_range_1000)[1] <- "naZero_EOO"
names(highUnc_naZero_geo_range_1000)[2] <- "naZero_AOO"

#Z-stat
## EOO
(highUnc.EOO - mean(highUnc_naMean_geo_range_1000$naZero_EOO)) / sd(highUnc_naMean_geo_range_1000$naZero_EOO)

#histogram
hist(highUnc_naMean_geo_range_1000$naZero_EOO,
  main = "L. wiedii extent of occurrence, with zero uncertainty values for NA cells")
abline(v = highUnc.EOO,
  col = "red")

#Z-stat
## AOO
(highUnc.AOO - mean(highUnc_naMean_geo_range_1000$naZero_AOO)) / sd(highUnc_naMean_geo_range_1000$naZero_AOO)

#histogram
hist(highUnc_naMean_geo_range_1000$naZero_AOO,
  main = "L. wiedii area of occupancy, with zero uncertainty values for NA cells")
abline(v = highUnc.AOO,
  col = "red")

----#100
  highUnc_naZero_geo_range_100 <-
  random_geo_range(
    100,
    highUnc_naZero,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(highUnc_naZero_geo_range_100)[1] <- "naZero_EOO"
names(highUnc_naZero_geo_range_100)[2] <- "naZero_AOO"

#Z-stat
## EOO
(highUnc.EOO - mean(highUnc_naZero_geo_range_100$naZero_EOO)) / sd(highUnc_naZero_geo_range_100$naZero_EOO)

#histogram
hist(highUnc_naZero_geo_range_100$naZero_EOO,
  main = "L. wiedii extent of occurrence, with zero uncertainty values for NA cells")
abline(v = highUnc.EOO,
  col = "red")

#Z-stat
## AOO
(highUnc.AOO - mean(highUnc_naZero_geo_range_100$naZero_AOO)) / sd(highUnc_naZero_geo_range_100$naZero_AOO)

#histogram
hist(highUnc_naZero_geo_range_100$naZero_AOO,
  main = "L. wiedii area of occupancy, with zero uncertainty values for NA cells")
abline(v = highUnc.AOO,
  col = "red")
```

`NA as NA`
```{r L_wiedii_low_naNA_geo_range}

----#1000
  highUnc_naNA_geo_range_1000 <-
  random_geo_range(
    1000,
    highUnc_naNA,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )

names(highUnc_naNA_geo_range_1000)[1] <- "naNA_EOO"
names(highUnc_naNA_geo_range_1000)[2] <- "naNA_AOO"

#Z-stat
## EOO
(highUnc.EOO - mean(highUnc_naNA_geo_range_1000$naNA_EOO)) / sd(highUnc_naNA_geo_range_1000$naNA_EOO)

#histogram
hist(highUnc_naNA_geo_range_1000$naNA_EOO,
  main = "L. wiedii extent of occurrence, without NA uncertainty cells")
abline(v = highUnc.EOO,
  col = "red")

#Z-stat
## AOO
(highUnc.AOO - mean(highUnc_naNA_geo_range_1000$naZero_AOO)) / sd(highUnc_naNA_geo_range_1000$naZero_AOO)

#histogram
hist(highUnc_naNA_geo_range_1000$naZero_AOO,
  main = "L. wiedii area of occupancy, without NA uncertainty cells")
abline(v = highUnc.AOO,
  col = "red")

----#100
  highUnc_naNA_geo_range_100 <-
  random_geo_range(
    100,
    highUnc_naNA,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )

names(highUnc_naNA_geo_range_100)[1] <- "naNA_EOO"
names(highUnc_naNA_geo_range_100)[2] <- "naNA_AOO"

#Z-stat
## EOO
(highUnc.EOO - mean(highUnc_naNA_geo_range_100$naNA_EOO)) / sd(highUnc_naNA_geo_range_100$naNA_EOO)

#histogram
hist(highUnc_naNA_geo_range_100$naNA_EOO,
  main = "L. wiedii extent of occurrence, with zero uncertainty values for NA cells")
abline(v = highUnc.EOO,
  col = "red")

#Z-stat
## AOO
(highUnc.EOO - mean(highUnc_naNA_geo_range_100$naNA_AOO)) / sd(highUnc_naNA_geo_range_100$naNA_AOO)

#histogram
hist(highUnc_naNA_geo_range_100$naNA_AOO,
  main = "L. wiedii area of occupancy, without NA uncertainty cells")
abline(v = highUnc.AOO,
  col = "red")
```

# Save Results as CSV
```{r csv iterations}
highUnc_100georanges <-
  cbind(
    highUnc_naMean_geo_range_100,
    highUnc_naZero_geo_range_100,
    highUnc_naNA_geo_range_100
  )
write.csv(highUnc_100georanges, "../Results/highUnc_100georanges.csv")

highUnc_1000georanges <-
  cbind(
    highUnc_naMean_geo_range_1000,
    highUnc_naZero_geo_range_1000,
    highUnc_naNA_geo_range_1000
  )
write.csv(highUnc_1000georanges,
  "../Results/highUnc_1000georanges.csv")
```
