---
title: "lowUnc-vignette"
author: "Samuel Chang"
date: "3/5/2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lowUnc-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# 1. Load the occUncertain R package and data set
```{r}
library(occUncertain)

load("../data/L_wiedii_lowUnc.RData")

lowUnc_observed <-
  dplyr::select(L_wiedii_lowUnc,
    decimalLatitude,
    decimalLongitude,
    species)

data(land)
lowUnc.IUCN <- IUCN.eval(lowUnc_observed, exclude.area = T, write_results = F)
lowUnc.EOO <- lowUnc.IUCN$EOO
lowUnc.AOO <- lowUnc.IUCN$AOO
```

# 2. meters_to_decdeg function
```{r uncertainty from meter to radian degrees}
#NA as Zero
L_wiedii_lowUnc_naZero <-
  meters_to_decdeg(
    L_wiedii_lowUnc,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as 0"
  )

L_wiedii_lowUnc_naZero <-
  cbind(L_wiedii_lowUnc, L_wiedii_lowUnc_naZero)

L_wiedii_lowUnc_naZero <- dplyr::select(L_wiedii_lowUnc_naZero, decimalLatitude,
    decimalLongitude,
    lon_uncertainty, lat_uncertainty, species)

#NA as Mean
L_wiedii_lowUnc_naMean <-
  meters_to_decdeg(
    L_wiedii_lowUnc,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as mean"
  )

L_wiedii_lowUnc_naMean <-
  cbind(L_wiedii_lowUnc, L_wiedii_lowUnc_naMean)

L_wiedii_lowUnc_naMean <- dplyr::select(L_wiedii_lowUnc_naMean, decimalLatitude,
    decimalLongitude,
    lon_uncertainty, lat_uncertainty, species)

#NA as NA
L_wiedii_lowUnc_naNA <-
  meters_to_decdeg(
    L_wiedii_lowUnc,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as NA"
  )

L_wiedii_lowUnc_naNA <-
  cbind(L_wiedii_lowUnc, L_wiedii_lowUnc_naNA)

L_wiedii_lowUnc_naNA <- dplyr::filter(L_wiedii_lowUnc_naNA, !is.na(coordinateUncertaintyInMeters))
L_wiedii_lowUnc_naNA <- dplyr::select(L_wiedii_lowUnc_naNA, decimalLatitude,
    decimalLongitude,
    lon_uncertainty, lat_uncertainty, species)

```

# 3. Using the random occurrences in land metrics with random_geo_range

`NA as Mean`
```{r L_wiedii_low_naMean geographic metrics}

---- 
      #1000 
L_wiedii_low_naMean_geo_range_1000 <-
  random_geo_range(
    1000,
    L_wiedii_lowUnc_naMean,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(L_wiedii_low_naMean_geo_range_1000)[1] <- "naMean_EOO"
names(L_wiedii_low_naMean_geo_range_1000)[2] <- "naMean_AOO"

#Z-stat
## EOO
(lowUnc.EOO - mean(L_wiedii_low_naMean_geo_range_1000$naMean_EOO)) / sd(L_wiedii_low_naMean_geo_range_1000$naMean_EOO)

#histogram
hist(L_wiedii_low_naMean_geo_range_1000$naMean_EOO,
  main = "L. wiedii extent of occurrence, with mean uncertainty values for NA cells")
abline(v = lowUnc.EOO,
  col = "red")

#Z-stat
## AOO
(lowUnc.AOO - mean(L_wiedii_low_naMean_geo_range_1000$naMean_AOO)) / sd(L_wiedii_low_naMean_geo_range_1000$naMean_AOO)

#histogram
hist(L_wiedii_low_naMean_geo_range_1000$naMean_AOO,
  main = "L. wiedii area of occupancy, with mean uncertainty values for NA cells")
abline(v = lowUnc.AOO,
  col = "red")

----
      #100
L_wiedii_low_naMean_geo_range_100 <-
  random_geo_range(
    100,
    L_wiedii_lowUnc_naMean,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(L_wiedii_low_naMean_geo_range_100)[1] <- "naMean_EOO"
names(L_wiedii_low_naMean_geo_range_100)[2] <- "naMean_AOO"

#Z-stat
## EOO
(lowUnc.EOO - mean(L_wiedii_low_naMean_geo_range_100$naMean_EOO)) / sd(L_wiedii_low_naMean_geo_range_100$naMean_EOO)

#histogram
hist(L_wiedii_low_naMean_geo_range_100$naMean_EOO,
  main = "L. wiedii extent of occurrence, with mean uncertainty values for NA cells")
abline(v = lowUnc.EOO,
  col = "red")

#Z-stat
## AOO
(lowUnc.AOO - mean(L_wiedii_low_naMean_geo_range_100$naMean_AOO)) / sd(L_wiedii_low_naMean_geo_range_100$naMean_AOO)

#histogram 
hist(L_wiedii_low_naMean_geo_range_100$naMean_AOO,
  main = "L. wiedii area of occupancy, with mean uncertainty values for NA cells")
abline(v = lowUnc.AOO,
  col = "red")
```

`naZero`
```{r L_wiedii_low_naZero_geo_range}
----
  
      #1000
L_wiedii_low_naZero_geo_range_1000 <-
  random_geo_range(
    1000,
    L_wiedii_lowUnc_naZero,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(L_wiedii_low_naZero_geo_range_1000)[1] <- "naZero_EOO"
names(L_wiedii_low_naZero_geo_range_1000)[2] <- "naZero_AOO"

#Z-stat
## EOO
(lowUnc.EOO - mean(L_wiedii_low_naMean_geo_range_1000$naZero_EOO)) / sd(L_wiedii_low_naMean_geo_range_1000$naZero_EOO)

#histogram
hist(L_wiedii_low_naMean_geo_range_1000$naZero_EOO,
  main = "L. wiedii extent of occurrence, with zero uncertainty values for NA cells")
abline(v = lowUnc.EOO,
  col = "red")

#Z-stat
## AOO
(lowUnc.AOO - mean(L_wiedii_low_naMean_geo_range_1000$naZero_AOO)) / sd(L_wiedii_low_naMean_geo_range_1000$naZero_AOO)

#histogram
hist(L_wiedii_low_naMean_geo_range_1000$naZero_AOO,
  main = "L. wiedii area of occupancy, with zero uncertainty values for NA cells")
abline(v = lowUnc.AOO,
  col = "red")

---- 
      #100 
L_wiedii_low_naZero_geo_range_100 <-
  random_geo_range(
    100,
    L_wiedii_lowUnc_naZero,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(L_wiedii_low_naZero_geo_range_100)[1] <- "naZero_EOO"
names(L_wiedii_low_naZero_geo_range_100)[2] <- "naZero_AOO"

#Z-stat
## EOO
(lowUnc.EOO - mean(L_wiedii_low_naZero_geo_range_100$naZero_EOO)) / sd(L_wiedii_low_naZero_geo_range_100$naZero_EOO)

#histogram
hist(L_wiedii_low_naZero_geo_range_100$naZero_EOO,
  main = "L. wiedii extent of occurrence, with zero uncertainty values for NA cells")
abline(v = lowUnc.EOO,
  col = "red")

#Z-stat
## AOO
(lowUnc.AOO - mean(L_wiedii_low_naZero_geo_range_100$naZero_AOO)) / sd(L_wiedii_low_naZero_geo_range_100$naZero_AOO)

#histogram
hist(L_wiedii_low_naZero_geo_range_100$naZero_AOO,
  main = "L. wiedii area of occupancy, with zero uncertainty values for NA cells")
abline(v = lowUnc.AOO,
  col = "red")

```

`NA as NA`
```{r L_wiedii_low_naNA_geo_range}

---- 
      #1000 
L_wiedii_low_naNA_geo_range_1000 <-
  random_geo_range(
    1000,
    L_wiedii_lowUnc_naNA,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )

names(L_wiedii_low_naNA_geo_range_1000)[1] <- "naNA_EOO"
names(L_wiedii_low_naNA_geo_range_1000)[2] <- "naNA_AOO"

#Z-stat
## EOO
(lowUnc.EOO - mean(L_wiedii_low_naNA_geo_range_1000$naNA_EOO)) / sd(L_wiedii_low_naNA_geo_range_1000$naNA_EOO)

#histogram
hist(L_wiedii_low_naNA_geo_range_1000$naNA_EOO,
  main = "L. wiedii extent of occurrence, without NA uncertainty cells")
abline(v = lowUnc.EOO,
  col = "red")

#Z-stat
## AOO
(lowUnc.AOO - mean(L_wiedii_low_naNA_geo_range_1000$naZero_AOO)) / sd(L_wiedii_low_naNA_geo_range_1000$naZero_AOO)

#histogram
hist(L_wiedii_low_naNA_geo_range_1000$naZero_AOO,
  main = "L. wiedii area of occupancy, without NA uncertainty cells")
abline(v = lowUnc.AOO,
  col = "red")

---- 
      #100
L_wiedii_low_naNA_geo_range_100 <-
  random_geo_range(
    100,
    L_wiedii_lowUnc_naNA,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )

names(L_wiedii_low_naNA_geo_range_100)[1] <- "naNA_EOO"
names(L_wiedii_low_naNA_geo_range_100)[2] <- "naNA_AOO"

#Z-stat
## EOO
(lowUnc.EOO - mean(L_wiedii_low_naNA_geo_range_100$naNA_EOO)) / sd(L_wiedii_low_naNA_geo_range_100$naNA_EOO)

#histogram
hist(L_wiedii_low_naNA_geo_range_100$naNA_EOO,
  main = "L. wiedii extent of occurrence, with zero uncertainty values for NA cells")
abline(v = lowUnc.EOO,
  col = "red")

#Z-stat
## AOO
(lowUnc.EOO - mean(L_wiedii_low_naNA_geo_range_100$naNA_AOO)) / sd(L_wiedii_low_naNA_geo_range_100$naNA_AOO)

#histogram
hist(L_wiedii_low_naNA_geo_range_100$naNA_AOO,
  main = "L. wiedii area of occupancy, without NA uncertainty cells")
abline(v = lowUnc.AOO,
  col = "red")
```

# Save Results as CSV
```{r csv iterations}
lowUnc_100georanges <-
  cbind(
    L_wiedii_low_naMean_geo_range_100,
    L_wiedii_low_naZero_geo_range_100,
    L_wiedii_low_naNA_geo_range_100
  )
write.csv(lowUnc_100georanges, "../Results/L_wiedii_low_100georanges.csv")

lowUnc_1000georanges <-
  cbind(
    L_wiedii_low_naMean_geo_range_1000,
    L_wiedii_low_naZero_geo_range_1000,
    L_wiedii_low_naNA_geo_range_1000
  )
write.csv(lowUnc_1000georanges, "../Results/lowUnc_1000georanges.csv" )
```
