---
title: "large_CO-vignette"
author: "Samuel Chang"
date: "3/5/2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{large_CO-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# 1. Load the occUncertain R package and large occurrence data set for T.ornatus in Colombia
```{r}
library(occUncertain)

load("../data/T_ornatus/T_ornatus_Co.rda")

large_observed <-
  dplyr::select(T_ornatus_Co,
    decimalLatitude,
    decimalLongitude,
    species)

data(land)
large.IUCN <- IUCN.eval(large_observed, exclude.area = T, write_results = F)
large.EOO <- large.IUCN$EOO #808
large.AOO <- large.IUCN$AOO #250297
```

# 2. meters_to_decdeg function
```{r uncertainty from meter to radian degrees}
#NA as Zero
large_naZero <-
  meters_to_decdeg(
    T_ornatus_Co,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as 0"
  )

large_naZero <-
  cbind(T_ornatus_Co, large_naZero)

large_naZero <- dplyr::select(large_naZero, decimalLatitude,
    decimalLongitude,
    lon_uncertainty, lat_uncertainty, species)

#NA as Mean
large_naMean <-
  meters_to_decdeg(
    T_ornatus_Co,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as mean"
  )

large_naMean <-
  cbind(T_ornatus_Co, large_naMean)

large_naMean <- dplyr::select(large_naMean, decimalLatitude,
    decimalLongitude,
    lon_uncertainty, lat_uncertainty, species)

#NA as NA
large_naNA <-
  meters_to_decdeg(
    T_ornatus_Co,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as NA"
  )

large_naNA <-
  cbind(T_ornatus_Co, large_naNA)

#removes the NA cells to use function random_geo_range with uses lat/lon uncertainty
large_naNA <-
  dplyr::filter(large_naNA,!is.na(coordinateUncertaintyInMeters))
large_naNA <- dplyr::select(
  large_naNA,
  decimalLatitude,
  decimalLongitude,
  lon_uncertainty,
  lat_uncertainty,
  species
)
```

# 3. Using the random occurrences in land metrics with random_geo_range

## `NA as Mean`
```{r large_naMean_geo_range}
#1000
#----
      
large_naMean_geo_range_1000 <-
  random_geo_range(
    1000,
    large_naMean,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(large_naMean_geo_range_1000)[1] <- "naMean_EOO"
names(large_naMean_geo_range_1000)[2] <- "naMean_AOO"

#Z-stat
## EOO
(large.EOO - mean(large_naMean_geo_range_1000$naMean_EOO)) / sd(large_naMean_geo_range_1000$naMean_EOO)

## AOO
(large.AOO - mean(large_naMean_geo_range_1000$naMean_AOO)) / sd(large_naMean_geo_range_1000$naMean_AOO)

##----
      #100
large_naMean_geo_range_100 <-
  random_geo_range(
    100,
    large_naMean,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(large_naMean_geo_range_100)[1] <- "naMean_EOO"
names(large_naMean_geo_range_100)[2] <- "naMean_AOO"

#Z-stat
## EOO --> -1.518511
(large.EOO - mean(large_naMean_geo_range_100$naMean_EOO)) / sd(large_naMean_geo_range_100$naMean_EOO)

## AOO --> -82.15066
(large.AOO - mean(large_naMean_geo_range_100$naMean_AOO)) / sd(large_naMean_geo_range_100$naMean_AOO)
```

## `Na as Zero`
```{r large_naZero_geo_range}
#1000
#----
large_naZero_geo_range_1000 <-
  random_geo_range(
    1000,
    large_naZero,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(large_naZero_geo_range_1000)[1] <- "naZero_EOO"
names(large_naZero_geo_range_1000)[2] <- "naZero_AOO"

#Z-stat
## EOO
(large.EOO - mean(large_naZero_geo_range_1000$naZero_EOO)) / sd(large_naZero_geo_range_1000$naZero_EOO)

## AOO
(large.AOO - mean(large_naZero_geo_range_1000$naZero_AOO)) / sd(large_naZero_geo_range_1000$naZero_AOO)

#---- 
      #100 
large_naZero_geo_range_100 <-
  random_geo_range(
    100,
    large_naZero,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )
names(large_naZero_geo_range_100)[1] <- "naZero_EOO"
names(large_naZero_geo_range_100)[2] <- "naZero_AOO"

#Z-stat
## EOO -- > -0.8588903
(large.EOO - mean(large_naZero_geo_range_100$naZero_EOO)) / sd(large_naZero_geo_range_100$naZero_EOO)

#Z-stat
## AOO --> -1.569794
(large.AOO - mean(large_naZero_geo_range_100$naZero_AOO)) / sd(large_naZero_geo_range_100$naZero_AOO)

```

## `NA as NA`
```{r L_wiedii_low_naNA_geo_range}
#1000
#---- 
large_naNA_geo_range_1000 <-
  random_geo_range(
    1000,
    large_naNA,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )

names(large_naNA_geo_range_1000)[1] <- "naNA_EOO"
names(large_naNA_geo_range_1000)[2] <- "naNA_AOO"

#Z-stat
## EOO
(large.EOO - mean(large_naNA_geo_range_1000$naNA_EOO)) / sd(large_naNA_geo_range_1000$naNA_EOO)

## AOO
(large.AOO - mean(large_naNA_geo_range_1000$naNA_AOO)) / sd(large_naNA_geo_range_1000$naNA_AOO)

#---- 
      #100
large_naNA_geo_range_100 <-
  random_geo_range(
    100,
    large_naNA,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty"
  )

names(large_naNA_geo_range_100)[1] <- "naNA_EOO"
names(large_naNA_geo_range_100)[2] <- "naNA_AOO"

#Z-stat
## EOO --> 2.865155
(large.EOO - mean(large_naNA_geo_range_100$naNA_EOO)) / sd(large_naNA_geo_range_100$naNA_EOO)

## AOO --> 307.84
(large.AOO - mean(large_naNA_geo_range_100$naNA_AOO)) / sd(large_naNA_geo_range_100$naNA_AOO)
```

# Save Results as rda
```{r save iterations}
large_100georanges <-
  cbind(
    large_naMean_geo_range_100,
    large_naZero_geo_range_100,
    large_naNA_geo_range_100)

save(large_100georanges, file = "../Results/Co_100georanges.rda")

large_1000georanges <-
  cbind(
    large_naMean_geo_range_1000,
    large_naZero_geo_range_1000,
    large_naNA_geo_range_1000
  )

save(large_1000georanges, file = "../Results/Co_1000georanges.rda")

```

```{r 100 iterations echo=FALSE, fig.width = 10, fig.height= 10}
library(ggplot2)
library(gridExtra)
library(grid)
library(ggrepel)

theme_set(theme_gray())

load("../Results/Co_100georanges.rda")
EOO_large_100georanges <- dplyr::select(large_100georanges, matches("EOO"))

AOO_large_100georanges <- dplyr::select(large_100georanges, matches("AOO"))


grid.arrange(
  ggplot(data = EOO_large_100georanges, aes(naMean_EOO)) + geom_histogram() +
    geom_vline(xintercept = large.EOO, color = "red"),
  ggplot(data = EOO_large_100georanges, aes(naZero_EOO)) + geom_histogram() +
    geom_vline(xintercept = large.EOO, color = "red"),
  ggplot(data = EOO_large_100georanges, aes(naNA_EOO)) + geom_histogram() +
    geom_vline(xintercept = large.EOO, color = "red"),
  ncol = 2,
  top = textGrob(
    "T. ornatus 100 EOO iterations using generated occurrences \n with degrees uncertainty and different NA_action parameters in Colombia",
    just = "center",
    gp = gpar(
      col = "blue",
      fontsize = 15,
      font = 3
    )
  )
)

grid.arrange(
  ggplot(data = AOO_large_100georanges, aes(naMean_AOO)) + geom_histogram() +
    geom_vline(xintercept = large.AOO, color = "red"),
  ggplot(data = AOO_large_100georanges, aes(naZero_AOO)) + geom_histogram() +
    geom_vline(xintercept = large.AOO, color = "red"),
  ggplot(data = AOO_large_100georanges, aes(naNA_AOO)) + geom_histogram() +
    geom_vline(xintercept = large.AOO, color = "red"),
  ncol = 2,
  top = textGrob(
    "T. ornatus 100 AOO iterations using generated occurrences \n with degrees uncertainty and different NA_action parameters in Colombia",
    just = "center",
    gp = gpar(
      col = "blue",
      fontsize = 15,
      font = 3
    )
  )
)
```
```{r 1000 iterations echo=FALSE, fig.width = 10, fig.height= 10}
library(ggplot2)
library(gridExtra)
library(grid)
library(ggrepel)

theme_set(theme_gray())

load("../Results/Co_100georanges.rda")
EOO_large_1000georanges <- dplyr::select(large_1000georanges, matches("EOO"))

AOO_large_1000georanges <- dplyr::select(large_1000georanges, matches("AOO"))


grid.arrange(
  ggplot(data = EOO_large_1000georanges, aes(naMean_EOO)) + geom_histogram() +
    geom_vline(xintercept = large.EOO, color = "red"),
  ggplot(data = EOO_large_1000georanges, aes(naZero_EOO)) + geom_histogram() +
    geom_vline(xintercept = large.EOO, color = "red"),
  ggplot(data = EOO_large_1000georanges, aes(naNA_EOO)) + geom_histogram() +
    geom_vline(xintercept = large.EOO, color = "red"),
  ncol = 2,
  top = textGrob(
    "T. ornatus 1000 EOO iterations using generated occurrences \n with degrees uncertainty and different NA_action parameters in Colombia",
    just = "center",
    gp = gpar(
      col = "blue",
      fontsize = 15,
      font = 3
    )
  )
)

grid.arrange(
  ggplot(data = AOO_large_1000georanges, aes(naMean_AOO)) + geom_histogram() +
    geom_vline(xintercept = large.AOO, color = "red"),
  ggplot(data = AOO_large_1000georanges, aes(naZero_AOO)) + geom_histogram() +
    geom_vline(xintercept = large.AOO, color = "red"),
  ggplot(data = AOO_large_1000georanges, aes(naNA_AOO)) + geom_histogram() +
    geom_vline(xintercept = large.AOO, color = "red"),
  ncol = 2,
  top = textGrob(
    "T. ornatus 1000 AOO iterations using generated occurrences \n with degrees uncertainty and different NA_action parameters in Colombia",
    just = "center",
    gp = gpar(
      col = "blue",
      fontsize = 15,
      font = 3
    )
  )
)
```

