---
title: "T_ornatus_EC-vignette"
author: "Samuel Chang"
date: "3/5/2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{T_ornatus_EC-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEnECding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  ECmment = "#>"
)
```


# 1. Load the occUncertain R package and small occurrence data set for T.ornatus in Ecuador
```{r}
library(occUncertain)
library(ConR)

load("../data/T_ornatus/Tremarctos_ornatus.rda")

full <-
  dplyr::select(Tremarctos_ornatus,
    decimalLatitude,
    decimalLongitude,
    species)

data(land)
full.IUCN <- IUCN.eval(full, exclude.area = T, write_results = F, DrawMap = TRUE, file_name="full_results")
full.EOO <- 385341.9 #full.IUCN$EOO #-->
full.AOO <- 1248 #--> full.IUCN$AOO 

full <-
  dplyr::select(Tremarctos_ornatus,
    decimalLatitude,
    decimalLongitude,
    coordinateUncertaintyInMeters,
    species)

summary(full$coordinateUncertaintyInMeters)
```

# 2. meters_to_decdeg function
```{r uncertainty from meter to radian degrees}
#NA as Zero
full_naZero <-
  meters_to_decdeg(
    full,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as 0"
  )

full_naZero <-
  cbind(full, full_naZero)

full_naZero <- dplyr::select(
  full_naZero,
  decimalLatitude,
  decimalLongitude,
  lon_uncertainty,
  lat_uncertainty,
  species
)
  
#NA as Mean
full_naMean <-
  meters_to_decdeg(
    full,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as mean"
  )

full_naMean <-
  cbind(full, full_naMean)

full_naMean <- dplyr::select(
  full_naMean,
  decimalLatitude,
  decimalLongitude,
  lon_uncertainty,
  lat_uncertainty,
  species
)

#NA as NA
full_naNA <-
  meters_to_decdeg(
    full,
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    distance = "coordinateUncertaintyInMeters",
    na_action = "NA as NA"
  )

full_naNA <-
  cbind(full, full_naNA)

#removes the NA cells to use function random_geo_range with uses lat/lon uncertainty
full_naNA <-
  dplyr::filter(full_naNA,!is.na(coordinateUncertaintyInMeters))

full_naNA <- dplyr::select(
  full_naNA,
  decimalLatitude,
  decimalLongitude,
  lon_uncertainty,
  lat_uncertainty,
  species
)
```

# 3. Using the random occurrences in land metrics with random_geo_range
## `NA as Mean`
```{r naMean_geo_range}
#1000 
#---- 
naMean_geo_range_1000 <-
  random_geo_range(
    1000,
    full_naMean,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty",
    country_map = land,
    exclude.area = T
  )
naMean_geo_range_1000$NA_action <- "NA as Mean"

#----
#100
naMean_geo_range_100 <-
  random_geo_range(
    100,
    full_naMean,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty",
    exclude.area = T
  )
naMean_geo_range_100$NA_action <- "NA as Mean"

#Z-stat
#100.EOO <- -2.765256
(full.EOO - mean(naMean_geo_range_100$EOO)) / sd(naMean_geo_range_100$EOO)

#100.AOO  <- -100.4125
(full.AOO - mean(naMean_geo_range_100$AOO)) / sd(naMean_geo_range_100$AOO)

#EOO.1k <- -2.603563
(full.EOO - mean(naMean_geo_range_1000$EOO)) / sd(naMean_geo_range_1000$EOO)

#AOO.1K <-  -89.80614
(full.AOO - mean(naMean_geo_range_1000$AOO)) / sd(naMean_geo_range_1000$AOO)
```

## `Na as Zero`
```{r naZero_geo_range}
#1000
#----
naZero_geo_range_1000 <-
  random_geo_range(
    1000,
    full_naZero,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty",
    exclude.area = T
  )
naZero_geo_range_1000$NA_action <- "NA as Zero"

#---- 
      #100 
naZero_geo_range_100 <-
  random_geo_range(
    100,
    full_naZero,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty",
    exclude.area = T
  )
naZero_geo_range_100$NA_action <- "NA as Zero"

#Z-stat
## EOO.100 --> -1.586518
(full.EOO - mean(naZero_geo_range_100$EOO)) / sd(naZero_geo_range_100$EOO)

## AOO.100  --> -5.665667
(full.AOO - mean(naZero_geo_range_100$AOO)) / sd(naZero_geo_range_100$AOO)

## EOO.1K --> -1.627137
(full.EOO - mean(naZero_geo_range_1000$EOO)) / sd(naZero_geo_range_1000$EOO)

## AOO.1K --> -5.726807
(full.AOO - mean(naZero_geo_range_1000$AOO)) / sd(naZero_geo_range_1000$AOO)

```

## `NA as NA`
```{r naNA_geo_range}
#1000
#---- 
naNA_geo_range_1000 <-
  random_geo_range(
    1000,
    full_naNA,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty",
    exclude.area = T
  )
naNA_geo_range_1000$NA_action <- "NA as NA"

#---- 
      #100
naNA_geo_range_100 <-
  random_geo_range(
    100,
    full_naNA,
    taxa_col = "species",
    lat_col = "decimalLatitude",
    lon_col = "decimalLongitude",
    lon_uncertainty = "lon_uncertainty",
    lat_uncertainty = "lat_uncertainty",
    exclude.area = T
  )
naNA_geo_range_100$NA_action <- "NA as NA"

#Z-stat
## 100.EOO --> 1.114009
(full.EOO - mean(naNA_geo_range_100$EOO)) / sd(naNA_geo_range_100$EOO)

## 100.AOO --> 165.9692
(full.AOO - mean(naNA_geo_range_100$AOO)) / sd(naNA_geo_range_100$AOO)
 
## EOO.1K --> 1.025156
(full.EOO - mean(naNA_geo_range_1000$EOO)) / sd(naNA_geo_range_1000$EOO)

## AOO.1K--> 145.8793
(full.AOO - mean(naNA_geo_range_1000$AOO)) / sd(naNA_geo_range_1000$AOO)
```

# Save Results as CSV
```{r csv iterations}
save(naMean_geo_range_100,
    naZero_geo_range_100,
    naNA_geo_range_100, file = "../Results/full_results/full_100.rda")

save(naMean_geo_range_1000,
    naZero_geo_range_1000,
    naNA_geo_range_1000, file = "../Results/full_results/full_1000.rda")
```

#Plots in a grid
```{r }
library(ggplot2)
library(cowplot)
library(scales)
library(gtable)

theme_set(theme_gray())

load("../Results/full_results/full_1000.rda")
load("../Results/full_results/full_100.rda")

full_1000georanges <- rbind(naMean_geo_range_1000,
                            naZero_geo_range_1000,
                            naNA_geo_range_1000)

full_100georanges <- rbind(naMean_geo_range_100,
                           naZero_geo_range_100,
                           naNA_geo_range_100)

EOO.1000 <-
  ggplot(full_1000georanges, aes(x = EOO, fill = as.factor(NA_action)))  +
  scale_fill_discrete(guide = FALSE) +
  geom_histogram(alpha = 0.6,
                 position = 'identity',
                 bins = 20) +
  scale_x_continuous(labels = comma ,
                     limits = c(283607.4, 563895.1)) +
  ylab("1000 iterations") +
  theme(
    plot.margin = margin(l = 0.5, unit = "cm"),
    axis.title.x = element_blank(),
    axis.title.y = element_text(
      hjust = 0.5,
      vjust = 7,
      face = "bold"
    )
  )

AOO.1000 <-
  ggplot(full_1000georanges, aes(x = AOO, fill = as.factor(NA_action)))  +
  scale_fill_discrete(guide = FALSE) +
  geom_histogram(alpha = 0.6,
                 position = 'identity',
                 bins = 20) +
  scale_x_continuous(labels = comma) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    plot.margin = margin(l = 0.7, unit = "cm")
  )

EOO.100 <-
  ggplot(full_100georanges, aes(x = EOO, fill = as.factor(NA_action)))  +
  scale_fill_discrete(guide = FALSE) +
  geom_histogram(alpha = 0.6,
                 position = 'identity',
                 bins = 20) +
  scale_x_continuous(labels = comma,
                     limits = c(283607.4, 563895.1)) +
  ylab("100 iterations") +
  theme(
    plot.margin = margin(l = 0.5, unit = "cm"),
    axis.title.y = element_text(
      hjust = 0.5,
      vjust = 7,
      face = "bold"
    ),
    axis.title.x = element_text(face = "bold")
  )

AOO.100 <-
  ggplot(full_100georanges, aes(x = AOO, fill = as.factor(NA_action)))  +
  scale_fill_discrete(name = "NA Parameters") +
  geom_histogram(alpha = 0.6,
                 position = 'identity',
                 bins = 20) +
  scale_x_continuous(labels = comma) +
  theme(
    axis.title.y = element_blank(),
    legend.position = "none",
    plot.margin = margin(l = 0.71, unit = "cm"),
    axis.title.x = element_text(face = "bold")
  )

full_plot <-
  plot_grid(
    EOO.1000,
    AOO.1000,
    EOO.100,
    AOO.100,
    ncol = 2,
    rel_widths = c(1, 1),
    rel_hights = c(1, 1),
    aling = 'hv',
    axis = "rlbt",
    labels = c("A", "B", "C", "D"),
    label_size = 8, 
    hjust = -2
    )
```
#Place the legend at the bottom.
```{r }
# extract a legend that is laid out horizontally
legend_b <- get_legend(
  AOO.100 + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

grid.arrange(full_plot, legend_b, ncol = 1)
#add space arpund edges
theme(plot.margin = unit(c(1,0.5,0.5,0.5), "cm")) 

# Suppress tick marks
p=full_plot+scale_y_continuous(breaks=NULL)+scale_x_continuous(breaks=NULL)

# Have to turn off clipping
gt <- ggplot_gtable(ggplot_build(p))
gt$layout$clip[gt$layout$name == "panel"] <- "off"

# need to draw it with the new clip settings
grid.draw(gt)


# add the legend underneath the row we made earlier. Give it 10%
# of the height of one plot (via rel_heights).
plot_grid(full_plot, legend_b, ncol = 1, rel_heights = c(620,.01))
```

#Save plot
```{r}
plot_legend <-
  ggplot(full_100georanges, aes(x = AOO, fill = as.factor(NA_action)))  +
  scale_fill_discrete(name = "NA Parameters")+
  geom_histogram(alpha = 0.6,
                 position = 'identity',
                 bins = 20)+
  theme(legend.position = "bottom")


legend = get_legend(plot_legend)
  
  gtable_filter(ggplot_gtable(
  ggplot_build(plot_legend)), "guide-box")

full <-
  plot_grid(full_plot, legend, ncol  = 1)


# [ggsave2] 
save_plot(
  plot= full_plot,
  filename = "full_plot_grid.png",
  base_width = 8,
  base_height = 5,
  units = "in",
  dpi = 96
)
```

