---
title: "Results"
author: "Samuel Chang"
date: "6/3/2020"
output: html_document
---

```{r datasets with low uncertainty }
#observed data set
load("../data/L_wiedii_lowUnc.RData")
observed <-
  dplyr::select(L_wiedii_lowUnc,
    decimalLatitude,
    decimalLongitude,
    species)
observed.EOO <- EOO.computing(observed, exclude.area = T, country_map = land)

L_wiedii_low_100georanges <-
  read_csv(
    "Results/L_wiedii_low_100georanges.csv",col_types = cols(X1 = col_skip(), X1_1 = col_skip())
  )

L_wiedii_low_1000georanges <- read_csv("Results/L_wiedii_low_1000georanges.csv")
```

```{r #na as Mean  z-stat and hist}
#Calculate a z-statistic for the EOO of the original data set compared to the EOO values of:

##100 itertion is -0.5995791 (493.31 sec elapsed)
(observed.EOO$EOO - mean(L_wiedii_low_100georanges$naMean_EOO)
) / sd(L_wiedii_low_100georanges$naMean_EOO)

hist(L_wiedii_low_100georanges$naMean_EOO,
  main = "L. wiediee extent of occurrence, with mean ucertainty values for NA cells")
abline(v = observed.EOO$EOO,
  col = "red")

#1000 iteration is -0.4048546
(observed.EOO$EOO - mean(L_wiedii_low_1000georanges$naMean_EOO)
) / sd(L_wiedii_low_1000georanges$naMean_EOO)

hist(L_wiedii_low_1000georanges$naMean_EOO,
  main = "L. wiediee extent of occurrence, with mean ucertainty values for NA cells")
abline(v = observed.EOO$EOO,
  col = "red")
```

```{r #na as Zero  z-stat and hist}
#Calculate a z-statistic for the EOO of the original data set compared to the EOO values of:

#100 itertion is -0.9961994
(observed.EOO$EOO - mean(L_wiedii_low_100georanges$naZero_EOO)
) / sd(L_wiedii_low_100georanges$naZero_EOO)

hist(L_wiedii_low_100georanges$naZero_EOO,
  main = "L. wiediee extent of occurrence, with mean ucertainty values for NA cells")
abline(v = observed.EOO$EOO,
  col = "red")

#1000 iteration is -0.8835011 --- 4551.01 sec elapsed
(observed.EOO$EOO - mean(L_wiedii_low_1000georanges$naZero_EOO)
) / sd(L_wiedii_low_1000georanges$naZero_EOO)

hist(L_wiedii_low_1000georanges$naZero_EOO,
  main = "L. wiediee extent of occurrence, with mean ucertainty values for NA cells")
abline(v = observed.EOO$EOO,
  col = "red")
```

```{r na as NA  z-stat and hist}
#Calculate a z-statistic for the EOO of the original data set compared to the EOO values of:

#100 itertion <- 2161.807
(observed.EOO$EOO - mean(L_wiedii_low_100georanges$naNA_EOO)
) / sd(L_wiedii_low_100georanges$naNA_EOO)

hist(L_wiedii_low_100georanges$naNA_EOO)
abline(v = observed.EOO$EOO,
  col = "red")

#1000 itertion <- 1963.668
(observed.EOO$EOO - mean(L_wiedii_low_1000georanges$naNA_EOO)
) / sd(L_wiedii_low_1000georanges$naNA_EOO)

hist(L_wiedii_low_1000georanges$naNA_EOO)
abline(v = observed.EOO$EOO, col = "red")
```

